# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' run_app
#' 
#' 
#' A quick shiny App to show the data the function is extracting
#' 
#' @import shiny
#' @import ggplot2
#' @importFrom unhcrthemes unhcr_pal theme_unhcr
#' @importFrom DT DTOutput
#' @importFrom stats reorder
#' @importFrom glue glue
#' @importFrom dplyr pull filter
#' @importFrom purrr map list_rbind
#' @importFrom scales pretty_breaks label_number cut_short_scale
#' 
#' @return nada
#' 
#' @export
#' @examples
#' 
#' ## Run the shiny App 
#' # run_app()
run_app <- function(){
ui <- fluidPage(
  h1("Retrieve Data From UNHCR Data Portal"),
  selectInput(inputId= "liste", 
              label = " then select a situation",
              choices = 
                unhcrdataportal::odp() |> 
                dplyr::filter(page_type =="situation" ) |>
                dplyr::pull(page_name) ),
                
              #  NULL ),
  
  actionButton("go", "Pull Data") ,
  tabsetPanel(type = "tabs",
              tabPanel("Plot",
                       plotOutput(outputId ="chart"),
                       " " ),
              tabPanel("Table",
                       DT::DTOutput(outputId = "table"),
                       " ")
              ),
  p("source code in package :",
    tags$a(href="https://github.com/Edouard-Legoupil/unhcrdataportal", "unhcrdataportal") )
    
)

server <- function(input, output, session) {
  ## create a reactive value to store what we have 
  reactiveObject <- reactiveValues(
    data = NULL,
    plot = NULL  )
  observeEvent(eventExpr = input$go, {
    data <- odp(page = as.character(input$liste),
                dataset = "population") |>
      ## extract the data
      purrr::map( "data") |>
      ## Bind together in a data frame
      purrr::list_rbind() 
    reactiveObject$data  <- data
    
    plot <- data |>
      ggplot() +
      geom_col(aes(x = as.integer(individuals),
                   y = stats::reorder( glue::glue("{population_group_name} \n as of {date}"),
                                       as.integer(individuals) )),
               fill = unhcrthemes::unhcr_pal(n = 1, "pal_blue"),
               width = 0.8) +
      labs(title = paste0(as.character(input$liste)),
           x = "Number of people",
           y = "",
           caption = "Source: UNHCR Data Portal: https://data.unhcr.org/en/situations \n\u00a9 UNHCR, The UN Refugee Agency") +
      scale_x_continuous(expand = expansion(c(0, 0.1)),
                         breaks = scales::pretty_breaks(n = 7),
                         labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
      unhcrthemes::theme_unhcr( font_size = 22, grid = "X",  axis = "y")
    
    reactiveObject$plot  <- plot
    
    ## console output in case..
    # cat(file=stderr(), 
    #     " List sit", 
    #     allsit ,"\n")
    
  })
  ## generate the plot
  output$chart <- renderPlot({
       reactiveObject$plot
    })
  ## generate the table
  output$table <- DT::renderDT({
           reactiveObject$data
    })
}

shinyApp(ui, server)
}
